name = "1.7.10 Ultimate Edition"
author = "PufferTeam"
version = "1.7.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e0af9867abbf89eecf497e054a5e7b8358037ebb372cf4cfff0934968b787aa"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
