name = "1.7.10 Ultimate Edition"
author = "PufferTeam"
version = "1.7.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96019d75cf7ae9b8f8c5b720c4cc58cb1c4bba86aaf74061e3fd730e7083f865"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
