name = "1.7.10 Ultimate Edition"
author = "PufferTeam"
version = "1.7.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b65f61b1d74b26c19eb7ffa4433ae876ff090c8b0c1e423dd5e2218d52e6b670"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
