name = "1.7.10 Ultimate Edition"
author = "PufferTeam"
version = "1.7.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8cba97129370349d260861432530bc2a9162567a0bc484c29efc4200467f322"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
